name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/run-integration.sh
          chmod +x ./scripts/wait-for-it.sh

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start PostgreSQL using Docker Compose
        run: docker-compose up -d

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run integration script
        run: npm run test:integration
