name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Make integration script executable
      run: chmod +x ./scripts/run-integration.sh

    - name: Make integration script executable
      run: chmod +x ./scripts/wait-for-it.sh

    - name: Run integration script
      run: npm run test:integration